"""init

Revision ID: 378f85b0f65d
Revises: 894b60288fc3
Create Date: 2024-04-24 14:58:37.387534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378f85b0f65d'
down_revision = '894b60288fc3'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
